name: Update Development Version Badge

on:
  push:
    branches:
      - main  

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get latest stable tag
        id: latest_tag
        uses: "WyriHaximus/github-action-get-latest-tag@v1"
        with:
          prefix: "v" 

      - name: Calculate commit count since last tag
        id: commit_count
        run: |

          count=$(git rev-list ${{ steps.latest_tag.outputs.tag }}..HEAD --count)
          echo "COMMIT_COUNT=$count" >> $GITHUB_ENV

          stable_version=$(echo "${{ steps.latest_tag.outputs.tag }}" | sed 's/^v//')
          echo "STABLE_VERSION=$stable_version" >> $GITHUB_ENV

      - name: Create JSON for badge
        run: |
          mkdir -p public
          echo '{' > public/version.json
          echo '  "schemaVersion": 1,' >> public/version.json
          echo '  "label": "Latest Dev Version",' >> public/version.json

          if [ ${{ env.COMMIT_COUNT }} -eq 0 ]; then
            echo '  "message": "${{ env.STABLE_VERSION }}",' >> public/version.json
          else
            echo '  "message": "${{ env.STABLE_VERSION }}-dev${{ env.COMMIT_COUNT }}",' >> public/version.json
          fi
          echo '  "color": "orange"' >> public/version.json
          echo '}' >> public/version.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          